task/urls.py
from django.urls import path

from task.views import (
    index,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)


urlpatterns = [
    path("", index, name="index"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "task"

to_do_list/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task"))
]  + debug_toolbar_urls()

task/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline_at = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        to="Tag",
        related_name="tasks",
        null=True,
        blank=True,
    )

    class Meta:
        ordering = (
            "is_completed",
            "-created_at",
        )

    def __str__(self) -> str:
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self) -> str:
        return self.name

task/forms.py
from django import forms

from task.models import Tag, Task


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    deadline_at = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        required=False
    )

    class Meta:
        model = Task
        fields = (
            "content",
            "deadline_at",
            "tags"
        )

task/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskForm
from task.models import Task, Tag


def index(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        task_id = request.POST.get("task_id")
        task = get_object_or_404(Task, id=task_id)
        if task.is_completed:
            task.is_completed = False
        else:
            task.is_completed = True
        task.save()
        return redirect("task:index")
    tasks = Task.objects.prefetch_related("tags")
    context = {
        "tasks": tasks
    }
    return render(request, "task/index.html", context=context)


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>TODO list</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
      type="text/css"/>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="{% url 'task:index' %}">
      Home
    </a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'task:tag-list' %}">
      Tags
    </a>
  </li>
</ul>

templates/task/index.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>TODO list</h1>
    <a class="btn btn-primary" href="{% url 'task:task-create' %}">
      Add a new task
    </a>
  </div>

  {% if tasks %}
    {% for task in tasks %}
      <div class="pb-2">
      <div class="card p-4 task">

        <div class="container">
          <div class="row h3">
            <div class="col-8 d-flex font-weight-bold">
              <p class="mr-1">
                {{ task }}
              </p>
              {% if task.is_completed %}
                <p class="ml-1 text-success">
                  Done
                </p>
              {% else %}
                <p class="ml-1 text-danger">
                  Not done
                </p>
              {% endif %}

            </div>
            <div class="col-4">
              <form method="post" action="">
                {% csrf_token %}
                <input type="hidden" name="task_id" value="{{ task.id }}">
                {% if task.is_completed %}
                  <button type="submit" class="btn btn-outline-dark">
                    Undo
                  </button>
                {% else %}
                  <button type="submit" class="btn btn-outline-success">
                    Complete
                  </button>
                {% endif %}


              </form>
            </div>
          </div>

        </div>

        <div class="container">
          <p>
            Created at: {{ task.created_at }}
          </p>
          {% if task.deadline_at %}
            <p class="text-warning font-weight-bold">
              Deadline: {{ task.deadline_at }}
            </p>
          {% endif %}
        </div>

        <div class="container">
          <div class="d-flex">
            <p class="mr-2">Tags: </p>
            {% for tag in task.tags.all %}
              <p class="mr-2">#{{ tag }}</p>
            {% empty %}
              <p class="mr-2">No tags</p>
            {% endfor %}
          </div>
          <div>
            <a href="{% url 'task:task-update' task.id %}"
               class="btn btn-outline-primary">
              <i class="bi-pen h3"></i>
            </a>
            <a href="{% url 'task:task-delete' task.id %}"
               class="btn btn-outline-danger">
              <i class="bi-trash h3"></i>
            </a>
          </div>

        </div>
      </div>
    {% endfor %}
  {% else %}
    No tasks yet. Create a new one.
  {% endif %}
{% endblock %}

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag: {{ tag }}?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a class="btn btn-secondary" href="{% url 'task:tag-list' %}">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>Tag list</h1>
    <a class="btn btn-primary" href="{% url 'task:tag-create' %}">
      Add a new tag
    </a>
  </div>
  {% if tag_list %}
    <table class="table table-hover align-middle">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'task:tag-update' tag.id %}">
              <i class="bi-pen h3"></i>
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'task:tag-delete' tag.id %}">
              <i class="bi-trash h3"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task: {{ task }}?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a class="btn btn-secondary" href="{% url 'task:index' %}">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}